### PR TITLE
Add a Standard function to execute Move Scripts inside the Move Modules

### PR DESCRIPTION
**Pull request by 0xAnto**
AIP to enable the execution of Move scripts from any Move modules.

### CODE REVIEW

**Comment by 0xAnto** [comment]
It is used for executing any functions without importing them into the module @wrwg. For example, let's consider a smart wallet module where the user should be able to execute any function. However, the current wallet module cannot achieve this because you have to import those functions into the wallet module in order to execute them. It is not practically possible to know all the functions in advance and add them to the module. Therefore, we need a way to enable users to execute any function without importing them into the module. That's why I suggest enabling script execution so that users can execute any required functions without importing them into the module.

**Comment by wrwg** [comment]
I don't see that what you are asking for is related to script execution. 

Rather, it appears you like to call an arbitrary function via the web APIs, in a generic way, where you e.g. specify name of the function and list of arguments. The Aptos CLI supports this already today. We can add this to the HTTP APIs as well if it is not there yet (@banool may have an opinion/insight about this).

However, there will still be the restriction that you can only call functions which the contract allows to call from the outside. This are entry and view functions. This is needed for security of the chain.

**Comment by wrwg** [comment]
Also, if you actually meant that Move code can call via some meta programming API arbitrary other Move code, than this a non-starter, sorry. This would violate a lot of the security principles build into Move, which prevent things like reentrance attacks as they are known from Eth. Move code can only call well-known other Move code, by design.

**Comment by ch4r10t33r** [comment]
> Also, if you actually meant that Move code can call via some meta programming API arbitrary other Move code, than this a non-starter, sorry. This would violate a lot of the security principles build into Move, which prevent things like reentrance attacks as they are known from Eth. Move code can only call well-known other Move code, by design.

Yes, we would like for Move to support reflection. We do understand that this has some security risks. But can you pls suggest us an alternative?

**Comment by wrwg** [comment]
> > Also, if you actually meant that Move code can call via some meta programming API arbitrary other Move code, than this a non-starter, sorry. This would violate a lot of the security principles build into Move, which prevent things like reentrance attacks as they are known from Eth. Move code can only call well-known other Move code, by design.
> 
> Yes, we would like to have the ability to execute any arbitrary code present in another move module. Effectively a kind of object reflection.
> 
> We do understand that this has some security risks. But can you please suggest us an alternative?

Apologies for the delay on answering, and thanks for your understanding about Move's core design principles. 

One workaround is to put your logic off-chain. Another one could be code generation: you generate Move code which dispatches to well-known call targets. I think this has been done by others before, however, this requires you to know the call targets ahead of time, and redeploy your contract the list of known target changes. Fortunately, Aptos supports code upgrade, so re-deploying is not a big deal. However, you need to keep in mind limits on code size.

Another technique I've heard mentioning is to somehow reverse the direction: instead of your generic code calling out into arbitrary other code, you let the other code call back into you. This avoids you having to hardcode the targets. However, it depends on what you plan to do, whether this works.

At some later point Move may also support a restricted, save form of dynamic dispatch. However, I still don't think the reflection like feature you are suggesting will make it into the language.

**Pull request closed without merging**
