### PR TITLE
AIP-82: Transaction Context Extension

### PR DESCRIPTION
**Pull request by junkil-park**

### CODE REVIEW

**Comment by e99243506bigplay** [comment]
Could we change gas payer to specific signer in smart contract? so sender no gas but still able to execute this function, paid by smart contract or someone else.

**Review by davidiw — APPROVED** [review]

**Comment by davidiw** [comment]
> Could we change gas payer to specific signer in smart contract? so sender no gas but still able to execute this function, paid by smart contract or someone else.

I think this belongs more as a feature request on aptos-core but also belongs to a more generic account abstraction model that's in the works.... good request.

**Comment by e99243506bigplay** [comment]
> > Could we change gas payer to specific signer in smart contract? so sender no gas but still able to execute this function, paid by smart contract or someone else.
> 
> I think this belongs more as a feature request on aptos-core but also belongs to a more generic account abstraction model that's in the works.... good request.

ah sorry, I mean, include conditional changing gas payer that if smart contract is successful to execute then wont cost gas otherwise transaction failed will sender cost that gas amount.

**Comment by davidiw** [comment]
> > > Could we change gas payer to specific signer in smart contract? so sender no gas but still able to execute this function, paid by smart contract or someone else.
> > 
> > 
> > I think this belongs more as a feature request on aptos-core but also belongs to a more generic account abstraction model that's in the works.... good request.
> 
> ah sorry, I mean, include conditional changing gas payer that if smart contract is successful to execute then smart contract will cost gas otherwise transaction failed will sender cost that gas amount.

It might be good to give an example, but again this is a behavioral change, this AIP is purely about exposing internal information about the transaction to the VM.

**Review by thepomeranian — APPROVED** [review]

**Pull request merged**
